; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -function-specialize -inline -instcombine -S < %s | FileCheck %s
target triple = "aarch64-unknown-linux-gnu"

@Global = internal constant i32 1, align 4

; Function Attrs: nofree nounwind uwtable
define internal void @recursiveFunc(i32* nocapture readonly %arg) {
  %temp = alloca i32, align 4
  %arg.load = load i32, i32* %arg, align 4
  %arg.cmp = icmp slt i32 %arg.load, 4
  br i1 %arg.cmp, label %block6, label %ret.block

block6:
  call void @print_val(i32 %arg.load)
  %arg.add = add nsw i32 %arg.load, 1
  store i32 %arg.add, i32* %temp, align 4
  call void @recursiveFunc(i32* nonnull %temp)
  br label %ret.block

ret.block:
  ret void
}

; Function Attrs: nofree nounwind
declare dso_local void @print_val(i32)

; Function Attrs: nofree nounwind uwtable
define i32 @main() {
; CHECK-LABEL: @main(
; CHECK-NEXT:    call void @print_val(i32 1)
; CHECK-NEXT:    call void @print_val(i32 2)
; CHECK-NEXT:    call void @print_val(i32 3)
; CHECK-NEXT:    ret i32 0
;
  call void @recursiveFunc(i32* nonnull @Global)
  ret i32 0
}
